language: ruby
cache:
- bundler
before_install:
- gem install bundler -v 2.0
install:
- bundle install
rvm:
- 2.4.1
notifications:
  email:
    recipients:
    - jacobmw@uber.com
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-docker.gemspec
- gem install sensu-plugins-docker-*.gem
before_deploy:
- bash -c "[ ! -d bonsai/ ] && git clone https://github.com/sensu/sensu-go-bonsai-asset.git bonsai || echo 'bonsai/ exists, skipping git clone'"
deploy:
- provider: rubygems
  api_key:
    secure: apocRGl3AyDyoKe0DfE8D9Cwcue7sW31US90bDpWJ6aAa2LGYiee+lusIRqp2IF2LDES8MqvyLV+Fxw6w5Cwzy6zmTIXSjwfQb0uMtjLNZMMJegxFx5ZtRwVDHJnMmrD5XVUJSfUPzjfk3im0iBGJpiHqusMbLbiNZBQO/EZspDUjhUL5C8X/lnfWGwmm9xCTaJYPDK4Am80n9hiEDTIQIHBvnQNspPIDby4LGiS44cMIp16/DvegxkFJ+A8WOsYX3DAUiajNI3WfjLqXaxdpEFPplGN19Lm5NSo9DZah6OZUjbasYQzNIZpO+0QMAYBCV/pDtWEOF/pUsiFqCnTPgzt2mxBpaGdqez+F9SNyVmnwqIe44G7yT3h4B5uMWkaixTnA2yLceNG0kHiSaj650HtHdulMC4si0V/6UQMyKXe0OEYJmA6UY5RbSNArpfCdFucZzC1xyOZPDY9v/bIc3e5/RQA6LRHH1EEVf8t6Ntp71tR5RC3Wpx/LpdlSXl6UuXTSWaQqunBTaMRDOV/brHyoTTaXqD6gbFizIBJhpBW/En8aY8bg36ZRmUPTFD92ZnVZr1Q6PWLCYMKMHxSvAHit+4zyz/sJ+FYgj67bXDJpTM4NpAUDbYhZkPNRl2flSCgG9LTyHQ2cpS5CCKcHNiU7Wp/2ztNZswzkR9kMmI=
  gem: sensu-plugins-docker
  on:
    tags: true
    all_branches: true
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-docker
- provider: script
  script: bonsai/ruby-runtime/travis-build-ruby-plugin-assets.sh sensu-plugins-docker
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    rvm: 2.4.1